/**
 * Represents a single video clip generated by the AI or queued for generation.
 * Belongs to a specific track and maps to a timeline range.
 */
export interface VideoClip {
    id: string;
    startTime: number;
    duration: number;
    endTime: number;
    track: number; // 1 or 2 for checkerboarding
    status: 'pending' | 'generating' | 'done' | 'error';
    videoPath?: string;
    generatedVideos?: string[]; // Array of generated video paths
    promptText?: string;
    source: 'main' | 'stem';
    stemName?: string;
    label: string;
    startImagePath?: string;
    endImagePath?: string;
}

/**
 * Represents a single row in the timeline UI, which can either be an active
 * clip or an unselected gap between clips.
 */
export interface TimelineRow {
    type: 'clip' | 'unselected';
    startTime: number;
    endTime: number;
    duration: number;
    clip?: VideoClip; // present when type === 'clip'
    label: string;
}

/**
 * Defines the user's current time selection on the waveform.
 * Used to dictate what segment will be sent for video generation.
 */
export interface SelectionState {
    source: 'main' | 'stem';
    stemIndex?: number;
    start: number;
    end: number;
}

/**
 * Represents an audio feature marker such as a beat or onset.
 * Rendered on the WaveSurfer timeline to help with syncing.
 */
export interface AudioMarker {
    time: number;
    type: 'beat' | 'onset' | 'loudness' | string;
    isDownbeat?: boolean;
    color?: string;
}

/**
 * Contains metadata and audio marker data for a specific stem track
 * (e.g., vocals, drums, bass).
 */
export interface StemData {
    type: string;
    url: string;
    path: string;
    color: string;
    markers: AudioMarker[];
}
