import type { ShotSize, ShotAngle, CameraMovement, LocationType } from './storyboard';

/**
 * Represents a single video clip generated by the AI or queued for generation.
 * Belongs to a specific track and maps to a timeline range.
 * Now unified with Storyboard metadata.
 */
export interface VideoClip {
    id: string;
    startTime: number;
    duration: number;
    endTime: number;
    track: number; // 1 or 2 for checkerboarding
    status: 'pending' | 'queued' | 'generating' | 'done' | 'error';
    videoPath?: string;
    generatedVideos?: string[]; // Array of generated video paths, if multiple variations exist
    source: 'main' | 'stem' | 'video';
    stemName?: string;
    label: string;
    startImagePath?: string;
    endImagePath?: string;

    // --- Storyboard & Narrative Metadata ---
    sceneNumber?: string;
    shotLetter?: string;
    /** 
     * Unified narrative fields. 
     * notes.action is also used as the AI prompt text. 
     */
    notes?: {
        action: string;
        dialogue: string;
        sound: string;
    };
    taggedElementIds?: string[];
    shotSize?: ShotSize;
    shotTypeAngle?: ShotAngle;
    cameraMovement?: CameraMovement;
    optics?: string;
    equipment?: string;
    locationType?: LocationType;
    vfxNotes?: string;
    paceWpm?: number;
}

/**
 * Represents a single row in the timeline UI rendering, which can either be an active
 * clip or an unselected gap between clips. Used to build a contiguous sequence of blocks.
 */
export interface TimelineRow {
    type: 'clip' | 'unselected';
    startTime: number;
    endTime: number;
    duration: number;
    clip?: VideoClip; // present when type === 'clip'
    label: string;
}

/**
 * Defines the user's current time selection on the waveform or video timeline.
 * Used to dictate what segment will be sent for video generation or playback ranges.
 */
export interface SelectionState {
    source: 'main' | 'stem' | 'video';
    stemIndex?: number;
    start: number;
    end: number;
}

/**
 * Represents an audio feature marker such as a beat or onset.
 * Rendered on the WaveSurfer timeline to help with syncing video clips to music.
 */
export interface AudioMarker {
    time: number;
    type: 'beat' | 'onset' | 'loudness' | string;
    isDownbeat?: boolean;
    color?: string; // Hex or rgba color string for rendering
}

/**
 * Contains metadata and audio marker data for a specific stem track
 * (e.g., vocals, drums, bass) resulting from source separation.
 */
export interface StemData {
    type: string;
    url: string;
    path: string;
    color: string;
    markers: AudioMarker[];
}

/**
 * Video metadata returned by FFprobe analysis.
 */
export interface VideoInfo {
    /** Video duration in seconds */
    duration: number;
    /** Frame rate (frames per second) */
    fps: number;
    /** Video width in pixels */
    width: number;
    /** Video height in pixels */
    height: number;
    /** Video codec name (e.g., "h264") */
    codec: string;
    /** Total number of frames (calculated) */
    totalFrames: number;
    /** Bitrate in kb/s */
    bitrate: number;
}

/**
 * A single extracted thumbnail frame from a video file.
 */
export interface VideoThumbnail {
    /** Absolute path to the thumbnail image file */
    path: string;
    /** Time in seconds this frame was extracted from */
    time: number;
}
