import type { ShotSize, ShotAngle, CameraMovement, LocationType } from './storyboard';

/**
 * Represents a single video clip generated by the AI or queued for generation.
 * Belongs to a specific track and maps to a timeline range.
 * Now unified with Storyboard metadata.
 */
export interface VideoClip {
    /** Unique identifier for the clip */
    id: string;
    /** Start time in seconds relative to the project timeline */
    startTime: number;
    /** Duration of the clip in seconds */
    duration: number;
    /** Calculated end time (startTime + duration) */
    endTime: number;
    /** Track index: 1 or 2. Used for 'checkerboarding' visuals in the timeline. */
    track: number;
    /** Current state of the generation job for this clip */
    status: 'pending' | 'queued' | 'generating' | 'done' | 'error';
    /** Absolute path to the currently active video file on disk */
    videoPath?: string;
    /** History of all generated variations for this clip */
    generatedVideos?: string[];
    /** Source of the audio/visual data: 'main' timeline, specific 'stem', or 'video' file */
    source: 'main' | 'stem' | 'video';
    /** If source is 'stem', which track (e.g., 'drums') */
    stemName?: string;
    /** Human-readable name for the shot (e.g., "Shot 1A") */
    label: string;
    /** Local or remote path to the start frame image */
    startImagePath?: string;
    /** Local or remote path to the end frame image */
    endImagePath?: string;
    /** AI-generated description of the start image content */
    actionDescription?: string;
    /** High-fidelity cinematic version of the prompt generated by LLM */
    aiExpandedPrompt?: string;
    /** Prevents AI from overwriting the expanded prompt when locked */
    expandedPromptLocked?: boolean;
    /** UI flag to indicate an active description generation job */
    isDescribing?: boolean;
    /** UI flag to indicate an active LLM expansion job */
    isExpanding?: boolean;

    // --- Storyboard & Narrative Metadata ---
    sceneNumber?: string;
    shotLetter?: string;
    /** 
     * Unified narrative fields. 
     * notes.action is the primary narrative prompt sent to the AI.
     */
    notes?: {
        action: string;
        dialogue: string;
        sound: string;
    };
    /** IDs of StoryboardAssets (characters/items) tagged in this shot */
    taggedElementIds?: string[];
    shotSize?: ShotSize;
    shotTypeAngle?: ShotAngle;
    cameraMovement?: CameraMovement;
    /** Optical parameters (e.g., "Anamorphic", "35mm") */
    optics?: string;
    equipment?: string;
    locationType?: LocationType;
    vfxNotes?: string;
    /** Words per minute used to auto-calculate duration from dialogue */
    paceWpm?: number;
}

/**
 * Represents a single row in the timeline UI rendering, which can either be an active
 * clip or an unselected gap between clips. Used to build a contiguous sequence of blocks.
 */
export interface TimelineRow {
    type: 'clip' | 'unselected';
    startTime: number;
    endTime: number;
    duration: number;
    clip?: VideoClip; // present when type === 'clip'
    label: string;
}

/**
 * Defines the user's current time selection on the waveform or video timeline.
 * Used to dictate what segment will be sent for video generation or playback ranges.
 */
export interface SelectionState {
    source: 'main' | 'stem' | 'video';
    stemIndex?: number;
    start: number;
    end: number;
}

/**
 * Represents an audio feature marker such as a beat or onset.
 * Rendered on the WaveSurfer timeline to help with syncing video clips to music.
 */
export interface AudioMarker {
    time: number;
    type: 'beat' | 'onset' | 'loudness' | string;
    isDownbeat?: boolean;
    color?: string; // Hex or rgba color string for rendering
}

/**
 * Contains metadata and audio marker data for a specific stem track
 * (e.g., vocals, drums, bass) resulting from source separation.
 */
export interface StemData {
    type: string;
    url: string;
    path: string;
    color: string;
    markers: AudioMarker[];
}

/**
 * Video metadata returned by FFprobe analysis.
 */
export interface VideoInfo {
    /** Video duration in seconds */
    duration: number;
    /** Frame rate (frames per second) */
    fps: number;
    /** Video width in pixels */
    width: number;
    /** Video height in pixels */
    height: number;
    /** Video codec name (e.g., "h264") */
    codec: string;
    /** Total number of frames (calculated) */
    totalFrames: number;
    /** Bitrate in kb/s */
    bitrate: number;
}

/**
 * A single extracted thumbnail frame from a video file.
 */
export interface VideoThumbnail {
    /** Absolute path to the thumbnail image file */
    path: string;
    /** Time in seconds this frame was extracted from */
    time: number;
}
